github: [gautamankoji]
patreon: gautamankoji
open_collective: gautamankoji
ko_fi: gautamankoji
tidelift: gautamankoji
community_bridge: gautamankoji
liberapay: gautamankoji
issuehunt: gautamankoji
otechie: gautamankoji
lfx_crowdfunding:
polar: gautamankoji
